# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_evidence_recevied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='recevied',
            new_name='received',
        ),
    ]
