# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170224_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=30)),
                ('engagementType', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='employer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
