# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170301_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='employer',
        ),
    ]
